const fs = require ('fs')
//fs.writeFileSync('catatan.txt', 'Nama Saya Bunga Aprillia')
//fs.appendFileSync('catatan.txt', 'Saya tinggal di Padang')

//const catatan = require('./catatan.js')
//const pesan = catatan()
//console.log(pesan)

const validator = require('validator')
const ambilCatatan = require('./catatan.js')
const pesan = ambilCatatan()
console.log(pesan)
console.log(validator.isURL('https://bunga.com'))

const chalk = require('chalk')
console.log(chalk.blue('print warna biru sukses'))
console.log(chalk.red.bold('Ini teks merah dan tebal yang sudah diubah!'))
console.log(chalk.green.italic('Ini teks hijau dan miring'))
console.log(chalk.hex('#FFA500').underline('Ini teks orange dan bergaris bawah'))
console.log(chalk.rgb(255, 192, 203).bgWhite('Ini teks pink dengan latar belakang putih'))
console.log(chalk.blue.bgYellow.inverse('Teks ini biru, latar kuning, dan warnanya terbalik'))